- name: Using variables here
  hosts: local
  connection: local
  vars_files:
  - common_vars.yaml
  tasks:
  - name: Use variables to print the message
    ansible.builtin.debug:
      msg: " {{ course }} is taught by {{ Trainer }} which is {{ Duration }}"
